import { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import { FileText, Clock, Send, AlertCircle, CheckCircle, X, ArrowLeft } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { Button } from './ui/button';

interface Invoice {
  id: string;
  clientName: string;
  amount: number;
  dueDate: string;
  daysOverdue: number;
  status: 'overdue' | 'due-soon' | 'paid';
  description: string;
}

interface InvoicesPageProps {
  onBack?: () => void;
}

export function InvoicesPage({ onBack }: InvoicesPageProps) {
  const { user } = useAuth();
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedInvoice, setSelectedInvoice] = useState<Invoice | null>(null);
  const [aiReminder, setAiReminder] = useState<string>('');
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    // In a real implementation, this would fetch from Firestore
    // For now, using mock data to demonstrate the UI
    const mockInvoices: Invoice[] = [
      {
        id: '1',
        clientName: 'Acme Corp',
        amount: 45000,
        dueDate: '2025-11-15',
        daysOverdue: 14,
        status: 'overdue',
        description: 'Website redesign project - Phase 1',
      },
      {
        id: '2',
        clientName: 'TechStart India',
        amount: 32000,
        dueDate: '2025-11-20',
        daysOverdue: 9,
        status: 'overdue',
        description: 'Mobile app development',
      },
      {
        id: '3',
        clientName: 'Digital Solutions',
        amount: 28000,
        dueDate: '2025-12-05',
        daysOverdue: 0,
        status: 'due-soon',
        description: 'SEO optimization services',
      },
    ];
    
    setInvoices(mockInvoices);
    setLoading(false);
  }, [user]);

  const handleGenerateReminder = async (invoice: Invoice) => {
    setGenerating(true);
    setSelectedInvoice(invoice);
    
    // Simulate AI generation (in real app, this calls the backend)
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    const reminder = `Subject: Friendly Reminder: Invoice #${invoice.id} - ₹${invoice.amount.toLocaleString('en-IN')}

Dear ${invoice.clientName} Team,

I hope this message finds you well! 

I wanted to reach out regarding Invoice #${invoice.id} for ${invoice.description}, totaling ₹${invoice.amount.toLocaleString('en-IN')}, which was due on ${new Date(invoice.dueDate).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}.

${invoice.daysOverdue > 0 ? `This invoice is now ${invoice.daysOverdue} days overdue. ` : ''}I understand that things can get busy, and I wanted to kindly check if there are any issues or questions regarding this invoice that I can help clarify.

Could you please confirm the payment status or expected payment date? Your prompt attention to this matter would be greatly appreciated.

Thank you for your continued partnership. Looking forward to hearing from you soon!

Best regards,
[Your Name]

---
💡 Generated by Chanakya, your AI financial assistant`;

    setAiReminder(reminder);
    setGenerating(false);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(aiReminder);
    // Could show a toast notification here
  };

  const statusColors = {
    overdue: 'bg-red-500/10 border-red-500/30 text-red-400',
    'due-soon': 'bg-yellow-500/10 border-yellow-500/30 text-yellow-400',
    paid: 'bg-green-500/10 border-green-500/30 text-green-400',
  };

  const statusIcons = {
    overdue: AlertCircle,
    'due-soon': Clock,
    paid: CheckCircle,
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-slate-950">
        <div className="text-white">Loading invoices...</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-black text-white pt-20 sm:pt-24 px-4 sm:px-6">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          {onBack && (
            <button
              onClick={onBack}
              className="flex items-center gap-2 text-gray-400 hover:text-white transition-colors mb-4"
            >
              <ArrowLeft className="w-5 h-5" />
              <span>Back to Dashboard</span>
            </button>
          )}
          <div className="flex items-center space-x-3 mb-2">
            <div className="p-3 bg-gradient-to-br from-amber-500 to-orange-600 rounded-xl">
              <FileText className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="text-3xl font-bold">Invoice Tracker</h1>
              <p className="text-slate-400">Chanakya's Invoice Hunter</p>
            </div>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-6">
            <div className="bg-slate-800/50 backdrop-blur-xl rounded-xl p-4 border border-slate-700/50">
              <div className="text-slate-400 text-sm mb-1">Total Outstanding</div>
              <div className="text-2xl font-bold">
                ₹{invoices.filter(i => i.status !== 'paid').reduce((sum, i) => sum + i.amount, 0).toLocaleString('en-IN')}
              </div>
            </div>
            <div className="bg-slate-800/50 backdrop-blur-xl rounded-xl p-4 border border-slate-700/50">
              <div className="text-slate-400 text-sm mb-1">Overdue Invoices</div>
              <div className="text-2xl font-bold text-red-400">
                {invoices.filter(i => i.status === 'overdue').length}
              </div>
            </div>
            <div className="bg-slate-800/50 backdrop-blur-xl rounded-xl p-4 border border-slate-700/50">
              <div className="text-slate-400 text-sm mb-1">Due Soon</div>
              <div className="text-2xl font-bold text-yellow-400">
                {invoices.filter(i => i.status === 'due-soon').length}
              </div>
            </div>
          </div>
        </div>

        {/* Invoices List */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="space-y-4">
            <h2 className="text-xl font-semibold mb-4">Your Invoices</h2>
            
            {invoices.map((invoice) => {
              const StatusIcon = statusIcons[invoice.status];
              
              return (
                <motion.div
                  key={invoice.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  className={`bg-slate-800/50 backdrop-blur-xl rounded-xl p-5 border cursor-pointer hover:bg-slate-800/70 transition-all ${
                    selectedInvoice?.id === invoice.id ? 'border-amber-500/50 ring-2 ring-amber-500/20' : 'border-slate-700/50'
                  }`}
                  onClick={() => setSelectedInvoice(invoice)}
                >
                  <div className="flex items-start justify-between mb-3">
                    <div>
                      <h3 className="font-semibold text-lg">{invoice.clientName}</h3>
                      <p className="text-slate-400 text-sm">{invoice.description}</p>
                    </div>
                    <div className={`px-3 py-1 rounded-full border text-xs font-medium ${statusColors[invoice.status]}`}>
                      <div className="flex items-center space-x-1">
                        <StatusIcon className="w-3 h-3" />
                        <span>{invoice.status === 'due-soon' ? 'Due Soon' : invoice.status === 'overdue' ? 'Overdue' : 'Paid'}</span>
                      </div>
                    </div>
                  </div>
                  
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="text-2xl font-bold">₹{invoice.amount.toLocaleString('en-IN')}</div>
                      <div className="text-slate-400 text-sm">
                        Due: {new Date(invoice.dueDate).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}
                        {invoice.daysOverdue > 0 && (
                          <span className="text-red-400 ml-2">({invoice.daysOverdue} days overdue)</span>
                        )}
                      </div>
                    </div>
                    
                    {invoice.status === 'overdue' && (
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          handleGenerateReminder(invoice);
                        }}
                        disabled={generating && selectedInvoice?.id === invoice.id}
                        className="bg-gradient-to-r from-amber-500 to-orange-600 text-white px-4 py-2 rounded-lg font-medium hover:from-amber-400 hover:to-orange-500 transition-all flex items-center space-x-2 disabled:opacity-50"
                      >
                        <Send className="w-4 h-4" />
                        <span>{generating && selectedInvoice?.id === invoice.id ? 'Generating...' : 'Chanakya, handle this'}</span>
                      </button>
                    )}
                  </div>
                </motion.div>
              );
            })}
          </div>

          {/* AI Reminder Preview */}
          <div>
            <h2 className="text-xl font-semibold mb-4">AI-Generated Reminder</h2>
            
            {!selectedInvoice && !aiReminder ? (
              <div className="bg-slate-800/30 backdrop-blur-xl rounded-xl p-8 border border-slate-700/50 text-center">
                <FileText className="w-16 h-16 text-slate-600 mx-auto mb-4" />
                <p className="text-slate-400">
                  Select an overdue invoice and click "Chanakya, handle this" to generate a professional reminder email
                </p>
              </div>
            ) : aiReminder ? (
              <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                className="bg-slate-800/50 backdrop-blur-xl rounded-xl border border-slate-700/50 overflow-hidden"
              >
                <div className="bg-gradient-to-r from-amber-500/10 to-orange-600/10 p-4 border-b border-slate-700/50">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-2">
                      <div className="p-2 bg-gradient-to-br from-amber-500 to-orange-600 rounded-lg">
                        <Send className="w-4 h-4 text-white" />
                      </div>
                      <div>
                        <h3 className="font-semibold">Ready to Send</h3>
                        <p className="text-xs text-slate-400">AI-crafted professional reminder</p>
                      </div>
                    </div>
                    <button
                      onClick={() => {
                        setAiReminder('');
                        setSelectedInvoice(null);
                      }}
                      className="text-slate-400 hover:text-white transition-colors"
                    >
                      <X className="w-5 h-5" />
                    </button>
                  </div>
                </div>
                
                <div className="p-6">
                  <pre className="text-sm text-slate-300 whitespace-pre-wrap font-mono leading-relaxed">
                    {aiReminder}
                  </pre>
                </div>
                
                <div className="p-4 bg-slate-900/50 border-t border-slate-700/50 flex space-x-3">
                  <button
                    onClick={copyToClipboard}
                    className="flex-1 bg-slate-700 text-white px-4 py-2.5 rounded-lg font-medium hover:bg-slate-600 transition-all"
                  >
                    Copy to Clipboard
                  </button>
                  <button
                    onClick={() => window.open(`mailto:?subject=Invoice Reminder&body=${encodeURIComponent(aiReminder)}`)}
                    className="flex-1 bg-gradient-to-r from-amber-500 to-orange-600 text-white px-4 py-2.5 rounded-lg font-medium hover:from-amber-400 hover:to-orange-500 transition-all"
                  >
                    Open in Email
                  </button>
                </div>
              </motion.div>
            ) : (
              <div className="bg-slate-800/50 backdrop-blur-xl rounded-xl p-8 border border-slate-700/50 text-center">
                <div className="animate-pulse">
                  <div className="w-12 h-12 bg-amber-500/20 rounded-full mx-auto mb-4" />
                  <p className="text-slate-400">Chanakya is crafting your reminder...</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
